/* ============================================
   xuan905 Skills — 技能資料庫
   ============================================ */

const SKILLS = [
  /* ── 🌿 哲學・信仰 ── */
  {
    id: 'taipei-bus-skill',
    name: '臺北市公車定點車機',
    name_en: 'Taipei Bus Tracker',
    slug: 'taipei-bus-skill',
    icon: '🚌',
    iconEmoji: '🚌',
    category: 'tools',
    categoryLabel: { 'zh-TW': '工具・系統', 'zh-CN': '工具・系统', 'en': 'Tools & Systems' },
    tagline: {
      'zh-TW': '公車即時動態・站序查詢・長者等車頁面',
      'zh-CN': '公交车即时动态・站序查询・长者等车页面',
      'en': 'Real-time Taipei bus tracking, stop sequence, elder-friendly wait page'
    },
    desc: {
      'zh-TW': '串接臺北市定點車機 API 與 PTX 開放資料，提供公車即時位置查詢、路線搜尋、站序 ETA 估算。另有「等公車」長者專用頁面，字體大、按鈕大、彩色倒數計時。',
      'zh-CN': '串接台北市定点车机 API 与 PTX 开放资料，提供公交车即时位置查询、路线搜索、站序 ETA 估算。另有「等公车」长者专用页面，字体大、按钮大、彩色倒数计时。',
      'en': 'Real-time Taipei bus location via vehicle API and PTX data — route search, stop sequence, ETA estimation. Includes an elder-friendly "wait for bus" page with large fonts, big buttons, and color countdown.'
    },
    accentColor: '#E85D04',
    accentBg: '#FFF0E6',
    clawhubUrl: 'https://clawhub.ai/skills/taipei-bus-skill',
    githubUrl: 'https://github.com/xuan905/taipei-bus-skill',
    siteUrl: 'https://xuan905.github.io/AI_Skills/bus/',
    installCmd: 'clawhub install taipei-bus-skill',
    keywords: ['臺北', '公車', 'bus', 'PTX', 'ETA', '即時', '等公車', '長者'],
    featured: true,
    tags: ['公車', 'PTX', '長者', '工具'],
  },
  {
    id: 'laozi-ai',
    name: '老子AI',
    name_en: 'Laozi AI',
    slug: 'laozi-ai',
    icon: '老',
    iconEmoji: '🧘',
    category: 'philosophy',
    categoryLabel: { 'zh-TW': '哲學・信仰', 'zh-CN': '哲学・信仰', 'en': 'Philosophy & Faith' },
    tagline: { 'zh-TW': '道德經81章，三語智慧', 'zh-CN': '道德经81章，三语智慧', 'en': 'Tao Te Ching 81 chapters, trilingual wisdom' },
    desc: {
      'zh-TW': '完整收錄《道德經》81章，含繁體、簡體、英文三語原文。支援主題查詢（道法自然、上善若水、無為而治）、每日一則、哲學解析與道家風格創作輔助。',
      'zh-CN': '完整收录《道德经》81章，含繁体、简体、英文三语原文。支持主题查询（道法自然、上善若水、无为而治）、每日一则、哲学解析与道家风格创作辅助。',
      'en': 'Complete 81 chapters of the Tao Te Ching in Traditional Chinese, Simplified Chinese, and English. Supports topic search (Wu Wei, Supreme Good Like Water), daily chapter rotation, philosophy analysis, and Taoist-style creative writing.'
    },
    accentColor: '#00B894',
    accentBg: '#E8FBF5',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/laozi-ai',
    githubUrl: 'https://github.com/xuan905/laozi-ai-skill',
    siteUrl: 'https://xuan905.github.io/laozi-ai-skill/',
    installCmd: 'clawhub install laozi-ai',
    keywords: ['道德經', '道家', '老子', '無為', '上善若水', 'Tao Te Ching', 'Laozi', 'Wu Wei'],
    featured: true,
    tags: ['哲學', '經典', '三語', '每日一則'],
  },
  {
    id: 'jesus-ai',
    name: '耶穌AI',
    name_en: 'Jesus AI',
    slug: 'jesus-ai-conversation',
    icon: '✝',
    iconEmoji: '✝',
    category: 'philosophy',
    categoryLabel: { 'zh-TW': '哲學・信仰', 'zh-CN': '哲学・信仰', 'en': 'Philosophy & Faith' },
    tagline: {
      'zh-TW': '18語言耶穌信仰陪伴，聖經故事與祈禱指引',
      'zh-CN': '18语言耶稣信仰陪伴，圣经故事与祈祷指引',
      'en': '18-language Jesus companion — Bible stories, prayer, faith guidance'
    },
    desc: {
      'zh-TW': '以耶穌的愛與教導為核心，提供信仰問答、祈禱指引、聖經故事、情感陪伴與生命方向建議。支援18種語言，溫柔聆聽，以提問引導思考。適合基督徒日常靈修與慕道友探索。',
      'zh-CN': '以耶稣的爱与教导为核心，提供信仰问答、祈祷指引、圣经故事、情感陪伴与生命方向建议。支持18种语言，温柔聆听，以提问引导思考。适合基督徒日常灵修与慕道友探索。',
      'en': 'Spiritual companion responding with the love and teachings of Jesus — faith questions, prayer guidance, Bible stories, emotional support, and life direction. 18 languages supported. Gentle listening, guided by questions.'
    },
    accentColor: '#E84393',
    accentBg: '#FFE8F0',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/jesus-ai-conversation',
    githubUrl: 'https://github.com/xuan905/jesus-ai-conversation',
    siteUrl: 'https://xuan905.github.io/jesus-ai-conversation/',
    installCmd: 'clawhub install jesus-ai-conversation',
    keywords: ['耶穌', '聖經', '祈禱', '信仰', '基督教', 'Jesus', 'Bible', 'Prayer'],
    featured: true,
    tags: ['信仰', '基督教', '靈修', '18語言'],
  },
  {
    id: 'buddha-ai',
    name: '佛陀AI',
    siteUrl: 'https://xuan905.github.io/buddha-quotes/',
    name_en: 'Buddha AI',
    slug: 'sakyamuni-buddha-skill',
    icon: '☸',
    iconEmoji: '☸',
    category: 'philosophy',
    categoryLabel: { 'zh-TW': '哲學・信仰', 'zh-CN': '哲学・信仰', 'en': 'Philosophy & Faith' },
    tagline: {
      'zh-TW': '18語言佛陀語錄，禪修與佛學智慧',
      'zh-CN': '18语言佛陀语录，禅修与佛学智慧',
      'en': '18-language Buddha wisdom — quotes, meditation, Buddhist philosophy'
    },
    desc: {
      'zh-TW': '收錄佛陀18種語言語錄、禪修指引與佛學概念解析。涵蓋四聖諦、八正道、緣起法等核心義理，協助修行者深化理解。支援18種語言即時切換。',
      'zh-CN': '收录佛陀18种语言语录、禅修指引与佛学概念解析。涵盖四圣谛、八正道、缘起法等核心义理，协助修行者深化理解。支持18种语言即时切换。',
      'en': 'Shakyamuni Buddha 18-language quote database with meditation guidance and Buddhist philosophy analysis. Covers Four Noble Truths, Eightfold Path, Pratītyasamutpāda. 18 language support.'
    },
    accentColor: '#FDCB6E',
    accentBg: '#FFF9E6',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/sakyamuni-buddha-skill',
    githubUrl: 'https://github.com/xuan905/sakyamuni-buddha-skill',
    installCmd: 'clawhub install sakyamuni-buddha-skill',
    keywords: ['佛陀', '佛教', '禪', '四聖諦', '八正道', 'Buddha', 'Zen', 'Meditation'],
    featured: false,
    tags: ['佛教', '禪修', '佛學', '18語言'],
  },
  {
    id: 'confucius-ai',
    name: '孔子AI',
    siteUrl: 'https://xuan905.github.io/confucius-ai-skill/',
    name_en: 'Confucius AI',
    slug: 'confucius-ai',
    icon: '儒',
    iconEmoji: '📜',
    category: 'philosophy',
    categoryLabel: { 'zh-TW': '哲學・信仰', 'zh-CN': '哲学・信仰', 'en': 'Philosophy & Faith' },
    tagline: {
      'zh-TW': '論語三語對照，儒家思想解析',
      'zh-CN': '论语三语对照，儒家思想解析',
      'en': 'Analects trilingual — Confucian wisdom in Chinese & English'
    },
    desc: {
      'zh-TW': '收錄《論語》完整原文，含繁體、簡體、英文三語翻譯。深入解析仁、義、禮、智、信等儒家核心概念，協助理解孔子思想與中華文化傳承。',
      'zh-CN': '收录《论语》完整原文，含繁体、简体、英文三语翻译。深入解析仁、义、礼、智、信等儒家核心概念，协助理解孔子思想与中华文化传承。',
      'en': 'Complete Analerta (論語) with trilingual text — Traditional Chinese, Simplified Chinese, and English translations. Deep dive into Ren, Yi, Li, Zhi, Xin and other Confucian core concepts.'
    },
    accentColor: '#636E72',
    accentBg: '#F0F0F0',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/confucius-ai',
    githubUrl: 'https://github.com/xuan905/confucius-ai-skill',
    installCmd: 'clawhub install confucius-ai',
    keywords: ['孔子', '論語', '儒家', '仁義', 'Confucius', 'Analects', 'Confucian'],
    featured: false,
    tags: ['儒學', '經典', '三語', '中華文化'],
  },

  /* ── 📚 知識・學習 ── */
  {
    id: 'bookshelf-plus',
    name: '圖書館管家 Plus',
    name_en: 'Bookshelf Plus',
    slug: 'bookshelf-plus',
    icon: '📚',
    iconEmoji: '📚',
    category: 'knowledge',
    categoryLabel: { 'zh-TW': '知識・學習', 'zh-CN': '知识・学习', 'en': 'Knowledge & Learning' },
    tagline: {
      'zh-TW': 'ISBN掃描入庫、借還追蹤、逾期提醒、Notion同步',
      'zh-CN': 'ISBN扫描入库、借还追踪、逾期提醒、Notion同步',
      'en': 'ISBN scan, lending tracker, overdue alerts, Notion sync'
    },
    desc: {
      'zh-TW': '個人書房管家：支援 ISBN 掃描與手動入庫、Google Books 資料自動補全、借還記錄追蹤、逾期提醒、書庫健康報告，並可同步至 Notion 長期保存。適合愛書人與圖書館管理者。',
      'zh-CN': '个人书房管家：支持 ISBN 扫描与手动入库、Google Books 资料自动补全、借还记录追踪、逾期提醒、书库健康报告，并可同步至 Notion 长期保存。适合爱书人与图书馆管理者。',
      'en': 'Personal book library manager with ISBN scan, auto-fill via Google Books, lending records, overdue alerts, library health report, and Notion sync. Perfect for avid readers and library managers.'
    },
    accentColor: '#0984E3',
    accentBg: '#EBF5FF',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/bookshelf-plus',
    githubUrl: 'https://github.com/xuan905/bookshelf-plus',
    siteUrl: null,
    installCmd: 'clawhub install bookshelf-plus',
    keywords: ['書', '圖書館', 'ISBN', '借書', 'Notion', 'Books', 'Library'],
    featured: true,
    tags: ['圖書管理', 'Notion', 'ISBN', '追蹤'],
  },
  {
    id: 'book-recommendation',
    name: '智能書籍推薦',
    name_en: 'Book Recommender',
    slug: 'book-recommendation-engine',
    icon: '📖',
    iconEmoji: '📖',
    category: 'knowledge',
    categoryLabel: { 'zh-TW': '知識・學習', 'zh-CN': '知识・学习', 'en': 'Knowledge & Learning' },
    tagline: {
      'zh-TW': '協同過濾、主題書單、Open Library 暢銷榜',
      'zh-CN': '协同过滤、主题书单、Open Library 畅销榜',
      'en': 'CF & content-based recommendation, Open Library bestseller'
    },
    desc: {
      'zh-TW': '智能書籍推薦引擎：結合協同過濾與內容相似度演算法，依閱讀歷史生成個人化書單；支援 Open Library 暢銷榜即時查詢、主題書單推薦與想讀追蹤功能。',
      'zh-CN': '智能书籍推荐引擎：结合协同过滤与内容相似度算法，依阅读历史生成个性化书单；支持 Open Library 畅销榜即时查询、主题书单推荐与想读追踪功能。',
      'en': 'Smart book recommendation engine combining collaborative filtering and content-based algorithms. Generates personalized reading lists, fetches Open Library bestsellers in real-time, theme-based recommendations and want-to-read tracking.'
    },
    accentColor: '#00B894',
    accentBg: '#E8FBF5',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/book-recommendation-engine',
    githubUrl: 'https://github.com/xuan905/book-recommendation-engine',
    siteUrl: null,
    installCmd: 'clawhub install book-recommendation-engine',
    keywords: ['書籍推薦', '推薦系統', '書單', 'Book Recommendation', 'CF'],
    featured: false,
    tags: ['推薦系統', '閱讀', '書單', '機器學習'],
  },

  /* ── 🎵 生活・創意 ── */
  {
    id: 'karaoke-companion',
    name: '卡拉OK伴侶',
    name_en: 'Karaoke Companion',
    slug: 'karaoke-companion',
    icon: '🎤',
    iconEmoji: '🎤',
    category: 'life',
    categoryLabel: { 'zh-TW': '生活・創意', 'zh-CN': '生活・创意', 'en': 'Life & Creative' },
    tagline: {
      'zh-TW': 'LRCLIB 即時歌詞、卡拉OK練習、填詞創作、翻譯對照',
      'zh-CN': 'LRCLIB 即时歌词、卡拉OK练习、填词创作、翻译对照',
      'en': 'LRCLIB real-time lyrics, karaoke practice, lyric creation & translation'
    },
    desc: {
      'zh-TW': '卡拉OK歌詞隨唱伴侶：從 LRCLIB 即時取得精準歌詞、支援時間軸同步，幫你練習唱歌、填詞創作，並提供中英翻譯對照，讓你更懂每首歌的意境。',
      'zh-CN': '卡拉OK歌词随唱伴侣：从 LRCLIB 即时取得精准歌词、支持时间轴同步，帮你练习唱歌、填词创作，并提供中英翻译对照，让你更懂每首歌的意境。',
      'en': 'Karaoke lyrics companion — fetches precise lyrics with timestamps from LRCLIB, supports real-time sync for singing practice, lyric writing, and Chinese-English translation comparison.'
    },
    accentColor: '#E84393',
    accentBg: '#FFE8F0',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/karaoke-companion',
    githubUrl: 'https://github.com/xuan905/karaoke-companion',
    siteUrl: null,
    installCmd: 'clawhub install karaoke-companion',
    keywords: ['卡拉OK', '歌詞', 'LRCLIB', '唱歌', 'Karaoke', 'Lyrics'],
    featured: true,
    tags: ['音樂', '唱歌', '歌詞', '翻譯'],
  },
  {
    id: 'guided-creative-artist',
    name: '引導式創作藝術家',
    name_en: 'Guided Creative Artist',
    slug: 'guided-creative-artist',
    icon: '藝',
    iconEmoji: '🎨',
    category: 'life',
    categoryLabel: { 'zh-TW': '生活·創意', 'zh-CN': '生活·创意', 'en': 'Life & Creative' },
    tagline: {
      'zh-TW': '天馬行空的想像共創，多平台生圖 Prompt 轉譯',
      'zh-CN': '天马行空的想象共创，多平台生图 Prompt 转译',
      'en': 'Wild imagination co-creation with multi-platform image prompts'
    },
    desc: {
      'zh-TW': 'AI 拋出奇異的場景種子，你回饋想像，AI 再把它接住、推得更遠。共創出畫面後，自動轉譯成 Midjourney、Stable Diffusion、DALL·E 3、Flux、即夢等平台的生圖 Prompt，甚至直接幫你把想像畫成圖片。',
      'zh-CN': 'AI 抛出奇异的场景种子，你反馈想象，AI 再把它接住、推得更远。共创出画面后，自动转译成 Midjourney、Stable Diffusion、DALL·E 3、Flux、即梦等平台的生图 Prompt，甚至直接帮你把想象画成图片。',
      'en': 'The AI throws out a strange seed of a scene, you feed back your imagination, and the AI catches it and pushes it further. When a vision takes shape, it translates into prompts for Midjourney, Stable Diffusion, DALL·E 3, Flux, Jimeng and more — or generates the image directly.'
    },
    accentColor: '#8B5CF6',
    accentBg: '#F3EEFF',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/guided-creative-artist',
    githubUrl: 'https://github.com/xuan905/guided-creative-artist',
    siteUrl: 'https://xuan905.github.io/guided-creative-artist/',
    installCmd: 'clawhub install guided-creative-artist',
    keywords: ['想像', '共創', '生圖', 'Prompt', 'Midjourney', 'Imagination', 'Co-creation'],
    featured: true,
    tags: ['創意', '想像力', '生圖', '共創'],
  },
  {
    id: 'emotion-monster',
    name: '情緒怪獸',
    name_en: 'Emotion Monster',
    slug: 'emotion-monster',
    icon: '🦄',
    iconEmoji: '🦄',
    category: 'life',
    categoryLabel: { 'zh-TW': '生活・創意', 'zh-CN': '生活・创意', 'en': 'Life & Creative' },
    tagline: {
      'zh-TW': '情緒識別、日記追蹤、心理陪伴',
      'zh-CN': '情绪识别、日记追踪、心理陪伴',
      'en': 'Emotion tracking, mood journal, mental wellness companion'
    },
    desc: {
      'zh-TW': '情緒怪獸是一個情緒陪伴與追蹤工具：協助你覺察當下情緒、記錄情緒日記、追蹤情緒趨勢，並以溫柔的方式提供心理陪伴與自我照護建議。',
      'zh-CN': '情绪怪兽是一个情绪陪伴与追踪工具：协助你觉察当下情绪、记录情绪日记、追踪情绪趋势，并以温柔的方式提供心理陪伴与自我照护建议。',
      'en': 'Emotion Monster is an emotional wellness companion — helps you identify feelings, keep a mood journal, track emotional trends, and provides gentle self-care guidance.'
    },
    accentColor: '#FDCB6E',
    accentBg: '#FFF9E6',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/emotion-monster',
    githubUrl: 'https://github.com/xuan905/emotion-monster',
    siteUrl: null,
    installCmd: 'clawhub install emotion-monster',
    keywords: ['情緒', '日記', '心理健康', '陪伴', 'Emotion', 'Mood', 'Wellness'],
    featured: false,
    tags: ['心理健康', '情緒追蹤', '日記', '陪伴'],
  },

  /* ── 🛠️ 工具・系統 ── */
  {
    id: 'smart-playlist-dj',
    name: '情境歌單 DJ',
    name_en: 'Smart Playlist DJ',
    slug: 'smart-playlist-dj',
    icon: '🎧',
    iconEmoji: '🎧',
    category: 'tools',
    categoryLabel: { 'zh-TW': '工具・系統', 'zh-CN': '工具・系统', 'en': 'Tools & Systems' },
    tagline: {
      'zh-TW': '自動偵測 mood / 天氣 / 時段，生成最佳歌單',
      'zh-CN': '自动侦测 mood / 天气 / 时段，生成最佳歌单',
      'en': 'Auto-detect mood, weather & time — generate the perfect playlist'
    },
    desc: {
      'zh-TW': '情境感知智慧播放列表：自動偵測你的心情、天氣與時段，配合時間（晨間、午後、夜晚）與天氣（晴、雨、陰），生成最符合當下情境的個人化音樂歌單。',
      'zh-CN': '情境感知智慧播放列表：自动侦测你的心情、天气与时段，配合时间（晨间、午后、夜晚）与天气（晴、雨、阴），生成最符合当下情境的个人化音乐歌单。',
      'en': 'Context-aware smart playlist — auto-detects your mood, weather and time of day (morning, afternoon, evening) to generate the perfect personalized music playlist for any occasion.'
    },
    accentColor: '#6C5CE7',
    accentBg: '#F0EEFF',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/smart-playlist-dj',
    githubUrl: 'https://github.com/xuan905/smart-playlist-dj',
    siteUrl: null,
    installCmd: 'clawhub install smart-playlist-dj',
    keywords: ['音樂', '歌單', '情境', 'Mood', 'Playlist', 'Weather'],
    featured: false,
    tags: ['音樂', '播放列表', 'AI', '情境感知'],
  },
  {
    id: 'opac-reader',
    name: 'OPAC 自動化工具',
    name_en: 'OPAC Automator',
    slug: 'opac-reader',
    icon: '🔍',
    iconEmoji: '🔍',
    category: 'tools',
    categoryLabel: { 'zh-TW': '工具・系統', 'zh-CN': '工具・系统', 'en': 'Tools & Systems' },
    tagline: {
      'zh-TW': '寶慶圖書館 M7 OPAC 自動化：登入、借閱、續借、搜尋',
      'zh-CN': '宝庆图书馆 M7 OPAC 自动化：登入、借阅、续借、搜寻',
      'en': 'Library OPAC automation — login, borrow, renew, search'
    },
    desc: {
      'zh-TW': '針對寶慶大學 M7 圖書館系統的自動化工具，支援自動登入、查詢借閱狀態、一鍵續借、書籍搜尋與逾期報告生成。節省手動操作時間，告別圖書館網頁的繁瑣操作。',
      'zh-CN': '针对宝庆大学 M7 图书馆系统的自动化工具，支持自动登入、查询借阅状态、一键续借、书籍搜寻与逾期报告生成。省去手动操作时间，告别图书馆网页的繁琐操作。',
      'en': 'Automation tool for Boqing University M7 library OPAC — auto login, check borrowing status, one-click renewals, book search, and overdue report generation. Saves time on library web operations.'
    },
    accentColor: '#636E72',
    accentBg: '#F0F0F0',
    clawhubUrl: null,
    githubUrl: 'https://github.com/xuan905/opac-reader',
    siteUrl: null,
    installCmd: null,
    keywords: ['OPAC', '圖書館', '自動化', '登入', '續借', 'Library', 'Automation'],
    featured: false,
    tags: ['圖書館', '自動化', 'OPAC', 'M7'],
  },
  {
    id: 'zhouyi-site-skill',
    name: '賽博周易',
    name_en: 'Cyber Zhouyi',
    slug: 'zhouyi-site-skill',
    icon: '易',
    iconEmoji: '☯️',
    category: 'philosophy',
    categoryLabel: { 'zh-TW': '哲學・信仰', 'zh-CN': '哲学・信仰', 'en': 'Philosophy & Faith' },
    tagline: {
      'zh-TW': '三幣起卦、64卦解讀與決策反思',
      'zh-CN': '三币起卦、64卦解读与决策反思',
      'en': 'Three-coin casting, 64 hexagrams & reflective decision guidance'
    },
    desc: {
      'zh-TW': '賽博周易把《易經》的觀察框架轉成可重複使用的 AI Skill：支援三幣六爻起卦、64 卦三語系詳細解讀、20 個生活問題快速載入、本機歷史紀錄與 JSON／PNG 分享卡片匯出。它不替你預言，而是把問題放回結構、節奏與可行動的下一步。',
      'zh-CN': '赛博周易把《易经》的观察框架转成可重复使用的 AI Skill：支持三币六爻起卦、64 卦三语详细解读、20 个生活问题快速载入、本机历史记录与 JSON／PNG 分享卡片导出。它不替你预言，而是把问题放回结构、节奏与可行动的下一步。',
      'en': 'Cyber Zhouyi turns the I Ching observation framework into a reusable AI Skill: three-coin casting, detailed 64-hexagram readings in three languages, 20 everyday prompts, local history, and JSON/PNG share-card export. It does not predict for you—it brings the question back to structure, rhythm, and an actionable next step.'
    },
    accentColor: '#A8793E',
    accentBg: '#F7F0E5',
    clawhubUrl: null,
    githubUrl: 'https://github.com/xuan905/cyber-zhouyi-official',
    siteUrl: 'https://xuan905.github.io/cyber-zhouyi-official/',
    installCmd: null,
    keywords: ['周易', '易經', '起卦', '六爻', '64卦', 'I Ching', 'Hexagram', 'Decision Reflection'],
    featured: true,
    tags: ['周易', '三幣法', '三語', '決策反思'],
  },
];

// 供 app.js 取用
const CATEGORIES = [
  { id: 'philosophy', key: 'catPhilosophy' },
  { id: 'knowledge',  key: 'catKnowledge'  },
  { id: 'life',       key: 'catLife'        },
  { id: 'tools',      key: 'catTools'       },
,
  {
    id: 'bedtime-story-teller',
    name: '睡前故事精靈',
    name_en: 'Bedtime Story Teller',
    slug: 'bedtime-story-teller',
    icon: '🌙',
    iconEmoji: '🌙',
    category: 'life',
    categoryLabel: { 'zh-TW': '生活・樂趣', 'zh-CN': '生活・乐趣', 'en': 'Life & Fun' },
    tagline: {
      'zh-TW': '用溫暖聲音為 2-6 歲孩童講床邊故事',
      'zh-CN': '用温暖声音为 2-6 岁孩童讲床边故事',
      'en': 'Warm bedtime stories for kids aged 2-6 with TTS voice'
    },
    desc: {
      'zh-TW': '睡前故事精靈，用溫暖聲音為 2-6 歲孩童講床邊故事。20+ 故事模板、免 API、支援 TTS 朗讀、故事收藏、睡前引導。',
      'zh-CN': '睡前故事精灵，用温暖声音为 2-6 岁孩童讲床边故事。20+ 故事模板、免 API、支持 TTS 朗读、故事收藏、睡前引导。',
      'en': 'Warm bedtime story teller for children aged 2-6. 20+ story templates, free API, TTS voice reading, story collection, bedtime guidance.'
    },
    accentColor: '#6C5CE7',
    accentBg: '#F0EDFF',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/bedtime-story-teller',
    githubUrl: 'https://github.com/xuan905/bedtime-story-teller',
    siteUrl: null,
    installCmd: 'clawhub install bedtime-story-teller',
    keywords: ['講故事','睡前故事','床邊故事','寶寶睡覺','晚安故事','說故事'],
    featured: false,
    tags: ['故事', '孩童', 'TTS', '家庭'],
  },
  {
    id: 'book-recommendation-engine',
    name: '書籍推薦引擎',
    name_en: 'Book Recommendation Engine',
    slug: 'book-recommendation-engine',
    icon: '🔥',
    iconEmoji: '🔥',
    category: 'knowledge',
    categoryLabel: { 'zh-TW': '知識・學習', 'zh-CN': '知识・学习', 'en': 'Knowledge & Learning' },
    tagline: {
      'zh-TW': '整合多種推薦演算法與即時書庫資料，幫你發現下一本好書',
      'zh-CN': '整合多种推荐算法与即时书库资料，帮你发现下一本好书',
      'en': '4 recommendation algorithms and Open Library search — discover your next great read'
    },
    desc: {
      'zh-TW': '書籍推薦引擎：支援協同過濾 / 內容相似度 / 熱門暢銷 / 標籤擴展四種演算法；內建 8 大主題書單；Open Library API 即時搜書；想讀書單追蹤含價格監控。',
      'zh-CN': '书籍推荐引擎：支持协同过滤 / 内容相似度 / 热门畅销 / 标签扩展四种算法；内置 8 大主题书单；Open Library API 即时搜书；想读书单追踪含价格监控。',
      'en': 'Book recommendation engine with 4 algorithms: collaborative filtering, content similarity, bestseller, and tag expansion. 8 built-in topic lists, Open Library API search, reading list with price tracking.'
    },
    accentColor: '#E17055',
    accentBg: '#FFF0EC',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/book-recommendation-engine',
    githubUrl: 'https://github.com/xuan905/book-recommendation-engine',
    siteUrl: null,
    installCmd: 'clawhub install book-recommendation-engine',
    keywords: ['推薦書','書籍推薦','找書','想讀什麼書','Open Library','主題書單','書單生成'],
    featured: false,
    tags: ['書本', '推薦系統', '學習'],
  },
  {
    id: 'ebook-converter-pro',
    name: '電子書轉換工具箱',
    name_en: 'Ebook Converter Pro',
    slug: 'ebook-converter-pro',
    icon: '📖',
    iconEmoji: '📖',
    category: 'tools',
    categoryLabel: { 'zh-TW': '工具・系統', 'zh-CN': '工具・系统', 'en': 'Tools & Systems' },
    tagline: {
      'zh-TW': '支援 EPUB / PDF / MOBI / AZW3 / FB2 → TXT / Markdown / HTML / JSON',
      'zh-CN': '支持 EPUB / PDF / MOBI / AZW3 / FB2 → TXT / Markdown / HTML / JSON',
      'en': 'Convert EPUB / PDF / MOBI / AZW3 / FB2 to TXT, Markdown, HTML, JSON'
    },
    desc: {
      'zh-TW': '電子書轉換工具箱：支援 EPUB / PDF / MOBI / AZW3 / FB2 → TXT / Markdown / HTML / JSON；批量轉換、封面萃取、元資料讀寫、圖書館自動分類。',
      'zh-CN': '电子书转换工具箱：支持 EPUB / PDF / MOBI / AZW3 / FB2 → TXT / Markdown / HTML / JSON；批量转换、封面萃取、元数据读写、图书馆自动分类。',
      'en': 'Ebook converter toolbox supporting EPUB, PDF, MOBI, AZW3, FB2 conversion to TXT, Markdown, HTML, JSON. Batch processing, cover extraction, metadata editing, auto-categorization.'
    },
    accentColor: '#00B894',
    accentBg: '#E8FBF5',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/ebook-converter-pro',
    githubUrl: 'https://github.com/xuan905/ebook-converter-pro',
    siteUrl: null,
    installCmd: 'clawhub install ebook-converter-pro',
    keywords: ['轉換電子書','EPUB 轉 TXT','PDF 轉 Markdown','批量轉檔','圖書整理','元資料','萃取封面'],
    featured: false,
    tags: ['電子書', '轉檔', '工具'],
  },
  {
    id: 'happy-brushing-hero',
    name: '快樂刷牙俠',
    name_en: 'Happy Brushing Hero',
    slug: 'happy-brushing-hero',
    icon: '🦷',
    iconEmoji: '🦷',
    category: 'life',
    categoryLabel: { 'zh-TW': '生活・樂趣', 'zh-CN': '生活・乐趣', 'en': 'Life & Fun' },
    tagline: {
      'zh-TW': '讓孩子愛上刷牙的歡樂計時器與打卡系統',
      'zh-CN': '让孩子爱上刷牙的欢乐计时器与打卡系统',
      'en': 'A fun timer & check-in system that makes kids love brushing teeth'
    },
    desc: {
      'zh-TW': '讓孩子愛上刷牙的歡樂計時器與打卡系統。用歡樂方式讓 2-6 歲孩童自願刷牙！計時 2 分鐘、音樂鼓勵、完成貼紙、連續打卡。',
      'zh-CN': '让孩子爱上刷牙的欢乐计时器与打卡系统。用欢乐方式让 2-6 岁孩童自愿刷牙！计时 2 分钟、音乐鼓励、完成贴纸、连续打卡。',
      'en': 'A fun tooth-brushing timer and check-in system for children aged 2-6. 2-minute timer, music encouragement, reward stickers, and streak tracking.'
    },
    accentColor: '#00CEC9',
    accentBg: '#E8FAFA',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/happy-brushing-hero',
    githubUrl: 'https://github.com/xuan905/happy-brushing-hero',
    siteUrl: null,
    installCmd: 'clawhub install happy-brushing-hero',
    keywords: ['刷牙','刷牙了沒','快去刷牙','牙齒','刷牙俠'],
    featured: false,
    tags: ['刷牙', '孩童', '健康', '遊戲'],
  },
  {
    id: 'my-library',
    name: '個人圖書館藏書管理',
    name_en: 'Personal Library Manager',
    slug: 'my-library',
    icon: '📚',
    iconEmoji: '📚',
    category: 'knowledge',
    categoryLabel: { 'zh-TW': '知識・學習', 'zh-CN': '知识・学习', 'en': 'Knowledge & Learning' },
    tagline: {
      'zh-TW': '支援查詢書庫、新增書籍、更新閱讀狀態與評分、分類統計、導出書單',
      'zh-CN': '支持查询书库、新增书籍、更新阅读状态与评分、分类统计、导出书单',
      'en': 'Query library, add books, track reading status & ratings, categorize & export'
    },
    desc: {
      'zh-TW': '查書、找書、新增藏書、統計書籍、生成書單、管理閱讀記錄。支援查詢書庫、新增書籍、更新閱讀狀態與評分、分類統計、導出書單。基於 Notion API。',
      'zh-CN': '查书、找书、新增藏书、统计书籍、生成书单、管理阅读记录。支持查询书库、新增书籍、更新阅读状态与评分、分类统计、导出书单。基于 Notion API。',
      'en': 'Personal library manager: search, add books, track reading status & ratings, categorize, and export reading lists. Built on Notion API.'
    },
    accentColor: '#0984E3',
    accentBg: '#EBF5FF',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/my-library',
    githubUrl: 'https://github.com/xuan905/my-library',
    siteUrl: null,
    installCmd: 'clawhub install my-library',
    keywords: ['查書','找書','新增藏書','統計書籍','生成書單','個人圖書館'],
    featured: false,
    tags: ['圖書管理', 'Notion', '閱讀'],
  },
  {
    id: 'reading-habit-tracker',
    name: '閱讀習慣追蹤系統',
    name_en: 'Reading Habit Tracker',
    slug: 'reading-habit-tracker',
    icon: '📊',
    iconEmoji: '📊',
    category: 'knowledge',
    categoryLabel: { 'zh-TW': '知識・學習', 'zh-CN': '知识・学习', 'en': 'Knowledge & Learning' },
    tagline: {
      'zh-TW': '目標設定、進度追蹤、分析報告、落後預警、視覺化統計',
      'zh-CN': '目标设定、进度追踪、分析报告、落后预警、可视化统计',
      'en': 'Goal setting, progress tracking, reports, lag alerts, visual stats'
    },
    desc: {
      'zh-TW': '目標設定（年目標/書單/頁數/時長）、進度追蹤、每週/每月分析報告、落後預警、視覺化統計。差異化：目標導向、計劃管理、深度數據分析。',
      'zh-CN': '目标设定（年目标/书单/页数/时长）、进度追踪、每周/每月分析报告、落后预警、可视化统计。差异化：目标导向、计划管理、深度数据分析。',
      'en': 'Reading habit tracker: set goals (annual/books/pages/time), track progress, weekly/monthly reports, lag alerts, and visual statistics.'
    },
    accentColor: '#6C5CE7',
    accentBg: '#F0EDFF',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/reading-habit-tracker',
    githubUrl: 'https://github.com/xuan905/reading-habit-tracker',
    siteUrl: null,
    installCmd: 'clawhub install reading-habit-tracker',
    keywords: ['閱讀目標','讀書計劃','每月閱讀','追蹤進度','閱讀統計','讀書報告'],
    featured: false,
    tags: ['閱讀', '目標管理', '數據分析'],
  },
  {
    id: 'reading-notes-genie',
    name: '閱讀筆記精靈',
    name_en: 'Reading Notes Genie',
    slug: 'reading-notes-genie',
    icon: '📖',
    iconEmoji: '📖',
    category: 'knowledge',
    categoryLabel: { 'zh-TW': '知識・學習', 'zh-CN': '知识・学习', 'en': 'Knowledge & Learning' },
    tagline: {
      'zh-TW': 'AI 自動生成章節摘要、精華語錄、讀書心得、知識點卡片',
      'zh-CN': 'AI 自动生成章节摘要、精华语录、读书心得、知识卡片',
      'en': 'AI generates chapter summaries, quotes, reviews & knowledge cards from any book'
    },
    desc: {
      'zh-TW': '輸入書名 / 上傳 PDF 或 EPUB，AI 自動生成章節摘要、精華語錄、讀書心得、知識點卡片，並匯出成 Markdown、Anki 卡片、PDF 等多種格式。',
      'zh-CN': '输入书名 / 上传 PDF 或 EPUB，AI 自动生成章节摘要、精华语录、读书心得、知识卡片，并导出成 Markdown、Anki 卡片、PDF 等多种格式。',
      'en': 'Input a book title or upload PDF/EPUB, AI auto-generates chapter summaries, quotes, reviews, and knowledge cards, exportable to Markdown, Anki cards, PDF and more.'
    },
    accentColor: '#FDCB6E',
    accentBg: '#FFF9E6',
    clawhubUrl: 'https://clawhub.ai/xuan905/skills/reading-notes-genie',
    githubUrl: 'https://github.com/xuan905/reading-notes-genie',
    siteUrl: null,
    installCmd: 'clawhub install reading-notes-genie',
    keywords: ['讀書筆記','做筆記','章節摘要','書摘','金句','知識卡片','PDF摘要'],
    featured: false,
    tags: ['讀書', '筆記', 'AI', '摘要'],
  },
];
